import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import MobileNav from "@/components/landingPage/MobileNav";

// Configure the Geist font
const geistFont = Geist({
  subsets: ["latin"],
  weight: ["400", "500", "600"], // Include the desired font weights
});

export const metadata: Metadata = {
  title: "Travel Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     < body className={`${geistFont.className} antialiased`}>
        <main className="pb-16 md:pb-0">
          {children}
        </main>
        <MobileNav />
      </body>
    </html>
  );
}
